console.log(1);

try {
    console.log(a);
} catch (error) {
    console.log("try里的代码报错");

}

console.log(2);